[platformio]
default_envs = heltec_v2_test, heltec_v3_test, heltec_v2_bridge, heltec_v3_bridge

[env]
platform = espressif32@6.12.0
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@7.6.0
build_flags =
    -D LORA_FREQUENCY_MHZ=915.0f
    -D LORA_BANDWIDTH_KHZ=250.0f
    -D LORA_SPREADING_FACTOR=7
    -D LORA_CODING_RATE=5
    -D LORA_TX_POWER_DBM=5
    -D LORA_SYNC_WORD=0x12

[env:heltec_v2_test]
board = heltec_wifi_lora_32_V2
build_flags =
    ${env.build_flags}
    -D HELTEC_TEST_MODE=1
    -D HELTEC_BOARD_V2=1
    -D NODE_ID=2

[env:heltec_v3_test]
board = heltec_wifi_lora_32_V3
build_flags =
    ${env.build_flags}
    -D HELTEC_TEST_MODE=1
    -D HELTEC_BOARD_V3=1
    -D NODE_ID=3

[env:heltec_v2_bridge]
board = heltec_wifi_lora_32_V2
build_flags =
    ${env.build_flags}
    -D HELTEC_BRIDGE_MODE=1
    -D HELTEC_BOARD_V2=1

[env:heltec_v3_bridge]
board = heltec_wifi_lora_32_V3
build_flags =
    ${env.build_flags}
    -D HELTEC_BRIDGE_MODE=1
    -D HELTEC_BOARD_V3=1
